import software.sava.build.publish.CentralPortalReleaseTask
import software.sava.build.publish.CentralPortalUploadTask

// Keep in sync with the Central Portal deployment setup in the root build.gradle.kts,
// which duplicates it because it cannot apply the convention plugins it produces.
plugins {
  id("maven-publish")
}

// Allow callers to drop further checksum files from the Maven Central deployment bundle
// via '-PmavenCentralExcludeChecksums=<extension>,...'; Central rejects one without .md5 and .sha1.
val mavenCentralExcludeChecksums = providers.gradleProperty("mavenCentralExcludeChecksums")
  .map { value -> value.split(",").map(String::trim).filter(String::isNotEmpty) }
  .getOrElse(emptyList())

// Central requires .md5 and .sha1 and validates nothing else. No resolver fetches a
// .sha256 or .sha512 sidecar in its default configuration (Gradle asks only for .sha1, and
// only to match a copy it already caches; Maven Resolver asks for SHA-1, then MD5), and .asc
// signatures need no checksums at all; every published file counts against Maven Central's
// monthly publishing limits. Restore the rest with '-PmavenCentralPublishAllChecksums=true'.
val defaultChecksumExcludes =
  if (providers.gradleProperty("mavenCentralPublishAllChecksums").getOrElse("false").toBoolean()) emptyList()
  else listOf("**/*.sha256", "**/*.sha512", "**/*.asc.md5", "**/*.asc.sha1")

// --- Central Portal deployment. Aggregated projects expose their staged publications
// through the 'savaCentralStagingElements' variant wired in
// 'software.sava.build.feature.publish'. 'nmcpAggregation' is kept as a deprecated alias
// of 'centralPortalAggregation' so existing consumer build files keep working. ---

val centralPortalAggregation = configurations.dependencyScope("centralPortalAggregation")
// Deprecated alias, named after the configuration the nmcp plugin used to provide;
// declare projects via 'centralPortalAggregation(project(":name"))' instead.
val nmcpAggregation = configurations.dependencyScope("nmcpAggregation")
val centralPortalStaging = configurations.resolvable("centralPortalStaging") {
  extendsFrom(centralPortalAggregation.get())
  extendsFrom(nmcpAggregation.get())
  attributes {
    attribute(Usage.USAGE_ATTRIBUTE, objects.named("sava-central-staging"))
  }
}

val zipCentralPortalDeployment = tasks.register<Zip>("zipCentralPortalDeployment") {
  group = "publishing"
  description = "Zips the staged publications of all aggregated projects into a Central Portal deployment bundle"
  from(centralPortalStaging)
  // Repository-level metadata is generated by publishing to the staging repositories but
  // has no place in a Central Portal deployment bundle.
  exclude("**/maven-metadata.xml*")
  defaultChecksumExcludes.forEach { pattern ->
    exclude(pattern)
  }
  mavenCentralExcludeChecksums.forEach { extension ->
    exclude("**/*.$extension")
  }
  destinationDirectory = layout.buildDirectory.dir("central-portal")
  archiveFileName = "deployment.zip"
}

// Resolved eagerly: computing this with provider 'map' lambdas would capture the script
// instance in the task state, which the configuration cache cannot serialize.
@Suppress("UnstableApiUsage")
val rootProjectName = isolated.rootProject.name
val deploymentVersion = providers.gradleProperty("version").getOrElse("")
val centralDeploymentName = if (deploymentVersion.isEmpty()) rootProjectName else "$rootProjectName $deploymentVersion"

val publishCentralPortalDeployment = tasks.register<CentralPortalUploadTask>("publishCentralPortalDeployment") {
  group = "publishing"
  description = "Uploads the Central Portal deployment bundle (USER_MANAGED: review and release in the portal UI)"
  bundle = zipCentralPortalDeployment.flatMap { it.archiveFile }
  username = providers.environmentVariable("MAVEN_CENTRAL_TOKEN")
  password = providers.environmentVariable("MAVEN_CENTRAL_SECRET")
  deploymentName = centralDeploymentName
}

// Releases a validated USER_MANAGED deployment without the portal UI:
//   ./gradlew releaseCentralPortalDeployment -PcentralPortalDeploymentId=<id>
tasks.register<CentralPortalReleaseTask>("releaseCentralPortalDeployment") {
  group = "publishing"
  description = "Publishes a validated Central Portal deployment ('-PcentralPortalDeploymentId=...')"
  deploymentId = providers.gradleProperty("centralPortalDeploymentId")
  username = providers.environmentVariable("MAVEN_CENTRAL_TOKEN")
  password = providers.environmentVariable("MAVEN_CENTRAL_SECRET")
}

// The task the release workflows invoke: every aggregated project uploads its own staged
// publications through the 'uploadToGitHubPackages' that 'software.sava.build.feature.publish'
// registers on it. Registered once the aggregation script has run, and only if the script
// did not register its own: scripts written before sava-build 21.6.0 do, and theirs keeps
// working through the deprecated task names 'software.sava.build.feature.publish' still
// provides, uploading the same way.
afterEvaluate {
  if ("publishToGitHubPackages" in tasks.names) {
    logger.warn(
      "Deprecated: {} registers its own 'publishToGitHubPackages'. Since sava-build 21.6.0 the " +
        "publish-maven-central plugin provides it for every project declared with " +
        "centralPortalAggregation(project(...)); declare the modules this task publishes that way, " +
        "then delete the registration.",
      buildFile
    )
  } else {
    val aggregated = listOf(centralPortalAggregation, nmcpAggregation)
      .flatMap { it.get().dependencies.withType<ProjectDependency>() }
      .map { it.path }
    tasks.register("publishToGitHubPackages") {
      group = "publishing"
      description = "Uploads every aggregated project's publications to GitHub Packages"
      dependsOn(aggregated.map { if (it == ":") ":uploadToGitHubPackages" else "$it:uploadToGitHubPackages" })
      // Without this a release would pass with nothing uploaded.
      val nothingAggregated = aggregated.isEmpty()
      doFirst {
        if (nothingAggregated) {
          throw GradleException(
            "No project to publish: declare each published module with " +
              "centralPortalAggregation(project(\":name\")) in the aggregation build script."
          )
        }
      }
    }
  }
}

// Deprecated alias, named after the task the nmcp plugin used to provide, so existing
// workflows keep working; invoke 'publishCentralPortalDeployment' instead.
tasks.register("publishAggregationToCentralPortal") {
  group = "publishing"
  description = "Deprecated alias for publishCentralPortalDeployment"
  dependsOn(publishCentralPortalDeployment)
}
