import software.sava.build.publish.CentralPortalReleaseTask
import software.sava.build.publish.CentralPortalUploadTask

// Keep in sync with the Central Portal deployment setup in the root build.gradle.kts,
// which duplicates it because it cannot apply the convention plugins it produces.
plugins {
  id("maven-publish")
}

// Allow callers to drop selected checksum files (e.g. md5, sha1, sha256, sha512) from the
// Maven Central deployment bundle via '-PmavenCentralExcludeChecksums=md5,sha1'.
val mavenCentralExcludeChecksums = providers.gradleProperty("mavenCentralExcludeChecksums")
  .map { value -> value.split(",").map(String::trim).filter(String::isNotEmpty) }
  .getOrElse(emptyList())

// --- Central Portal deployment. Aggregated projects expose their staged publications
// through the 'savaCentralStagingElements' variant wired in
// 'software.sava.build.feature.publish'. 'nmcpAggregation' is kept as a deprecated alias
// of 'centralPortalAggregation' so existing consumer build files keep working. ---

val centralPortalAggregation = configurations.dependencyScope("centralPortalAggregation")
// Deprecated alias, named after the configuration the nmcp plugin used to provide;
// declare projects via 'centralPortalAggregation(project(":name"))' instead.
val nmcpAggregation = configurations.dependencyScope("nmcpAggregation")
val centralPortalStaging = configurations.resolvable("centralPortalStaging") {
  extendsFrom(centralPortalAggregation.get())
  extendsFrom(nmcpAggregation.get())
  attributes {
    attribute(Usage.USAGE_ATTRIBUTE, objects.named("sava-central-staging"))
  }
}

val zipCentralPortalDeployment = tasks.register<Zip>("zipCentralPortalDeployment") {
  group = "publishing"
  description = "Zips the staged publications of all aggregated projects into a Central Portal deployment bundle"
  from(centralPortalStaging)
  // Repository-level metadata is generated by publishing to the staging repositories but
  // has no place in a Central Portal deployment bundle.
  exclude("**/maven-metadata.xml*")
  mavenCentralExcludeChecksums.forEach { extension ->
    exclude("**/*.$extension")
  }
  destinationDirectory = layout.buildDirectory.dir("central-portal")
  archiveFileName = "deployment.zip"
}

// Resolved eagerly: computing this with provider 'map' lambdas would capture the script
// instance in the task state, which the configuration cache cannot serialize.
@Suppress("UnstableApiUsage")
val rootProjectName = isolated.rootProject.name
val deploymentVersion = providers.gradleProperty("version").getOrElse("")
val centralDeploymentName = if (deploymentVersion.isEmpty()) rootProjectName else "$rootProjectName $deploymentVersion"

val publishCentralPortalDeployment = tasks.register<CentralPortalUploadTask>("publishCentralPortalDeployment") {
  group = "publishing"
  description = "Uploads the Central Portal deployment bundle (USER_MANAGED: review and release in the portal UI)"
  bundle = zipCentralPortalDeployment.flatMap { it.archiveFile }
  username = providers.environmentVariable("MAVEN_CENTRAL_TOKEN")
  password = providers.environmentVariable("MAVEN_CENTRAL_SECRET")
  deploymentName = centralDeploymentName
}

// Releases a validated USER_MANAGED deployment without the portal UI:
//   ./gradlew releaseCentralPortalDeployment -PcentralPortalDeploymentId=<id>
tasks.register<CentralPortalReleaseTask>("releaseCentralPortalDeployment") {
  group = "publishing"
  description = "Publishes a validated Central Portal deployment ('-PcentralPortalDeploymentId=...')"
  deploymentId = providers.gradleProperty("centralPortalDeploymentId")
  username = providers.environmentVariable("MAVEN_CENTRAL_TOKEN")
  password = providers.environmentVariable("MAVEN_CENTRAL_SECRET")
}

// Deprecated alias, named after the task the nmcp plugin used to provide, so existing
// workflows keep working; invoke 'publishCentralPortalDeployment' instead.
tasks.register("publishAggregationToCentralPortal") {
  group = "publishing"
  description = "Deprecated alias for publishCentralPortalDeployment"
  dependsOn(publishCentralPortalDeployment)
}
