name: Release Please

on:
  workflow_run:
    workflows: [ "Gradle Check" ]
    branches:
      - main
    types:
      - completed

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/release-please.yml
    secrets: inherit
